package com.paymentoptions.pos.network

object ApiEndpoints {
    const val SIGN_IN = "auth/signIn/"
    const val SIGN_OUT = "auth/signOut/"
    const val REFRESH_TOKEN = "auth/refreshToken/"
    const val COMPLETE_REGISTRATION = "entities/merchant/devices/complete-registration"
    const val DEVICE_CONFIGURATION = "entities/merchant/devices/external/configuration"
    const val TRANSACTION_LIST = "transactions/list"
    const val TRANSACTION_LIST_V2 = "transactions/daspay-list"
    const val PAY_BY_LINK = "paybylink/add/DASMID/"
    const val REFUND = "daspay/refund"
    const val VOID = "daspay/void"
    const val PAYMENT = "server-to-server-interface/daspay/payment"
    const val PAYMENT_STATUS = "notification/payments/webhook/notify/minesec"
    const val CATEGORY_LIST = "entities/merchant/catalog/all-categories/{merchantId}"
    const val PRODUCT_LIST = "entities/merchant/catalog/all-products/{categoryId}"
    const val INSIGHTS = "daspay/transactions/list"
    const val STATS_V2 = "transactions/stats"
    const val PAYMENT_DETAILS = "transactions/"
    const val UPLOAD_SIGNATURE = "entities/minesec/generate-image"
    const val ADD_PRODUCT = "entities/merchant/catalog/products"
    const val EDIT_PRODUCT = "entities/merchant/catalog/products/"
    const val UPLOAD_PRODUCT_IMAGE = "entities/merchant/catalog/upload-products-images"
    const val APP_CONFIGURATION = "dasconfig/daspay-configuration?"
    const val SETTLEMENT_LIST = "daspay/master/batch/list?"
    const val SETTLE_BATCH = "daspay/settle"
    const val GET_SIGNATURE = "transactions/daspay/check-image/"
}